/* This file was generated by SableCC (http://www.sablecc.org/). */

package checker.node;

import checker.analysis.*;

@SuppressWarnings("nls")
public final class ACastTerm extends PTerm
{
    private TLSq _lSq_;
    private TIdentifier _identifier_;
    private TRSq _rSq_;
    private PNonLeftRecTerm _nonLeftRecTerm_;

    public ACastTerm()
    {
        // Constructor
    }

    public ACastTerm(
        @SuppressWarnings("hiding") TLSq _lSq_,
        @SuppressWarnings("hiding") TIdentifier _identifier_,
        @SuppressWarnings("hiding") TRSq _rSq_,
        @SuppressWarnings("hiding") PNonLeftRecTerm _nonLeftRecTerm_)
    {
        // Constructor
        setLSq(_lSq_);

        setIdentifier(_identifier_);

        setRSq(_rSq_);

        setNonLeftRecTerm(_nonLeftRecTerm_);

    }

    @Override
    public Object clone()
    {
        return new ACastTerm(
            cloneNode(this._lSq_),
            cloneNode(this._identifier_),
            cloneNode(this._rSq_),
            cloneNode(this._nonLeftRecTerm_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACastTerm(this);
    }

    public TLSq getLSq()
    {
        return this._lSq_;
    }

    public void setLSq(TLSq node)
    {
        if(this._lSq_ != null)
        {
            this._lSq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lSq_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    public TRSq getRSq()
    {
        return this._rSq_;
    }

    public void setRSq(TRSq node)
    {
        if(this._rSq_ != null)
        {
            this._rSq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rSq_ = node;
    }

    public PNonLeftRecTerm getNonLeftRecTerm()
    {
        return this._nonLeftRecTerm_;
    }

    public void setNonLeftRecTerm(PNonLeftRecTerm node)
    {
        if(this._nonLeftRecTerm_ != null)
        {
            this._nonLeftRecTerm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nonLeftRecTerm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lSq_)
            + toString(this._identifier_)
            + toString(this._rSq_)
            + toString(this._nonLeftRecTerm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lSq_ == child)
        {
            this._lSq_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        if(this._rSq_ == child)
        {
            this._rSq_ = null;
            return;
        }

        if(this._nonLeftRecTerm_ == child)
        {
            this._nonLeftRecTerm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lSq_ == oldChild)
        {
            setLSq((TLSq) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        if(this._rSq_ == oldChild)
        {
            setRSq((TRSq) newChild);
            return;
        }

        if(this._nonLeftRecTerm_ == oldChild)
        {
            setNonLeftRecTerm((PNonLeftRecTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
