/* This file was generated by SableCC (http://www.sablecc.org/). */

package checker.node;

import checker.analysis.*;

@SuppressWarnings("nls")
public final class ACommaField extends PCommaField
{
    private TComma _comma_;
    private PFieldName _fieldName_;

    public ACommaField()
    {
        // Constructor
    }

    public ACommaField(
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") PFieldName _fieldName_)
    {
        // Constructor
        setComma(_comma_);

        setFieldName(_fieldName_);

    }

    @Override
    public Object clone()
    {
        return new ACommaField(
            cloneNode(this._comma_),
            cloneNode(this._fieldName_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACommaField(this);
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public PFieldName getFieldName()
    {
        return this._fieldName_;
    }

    public void setFieldName(PFieldName node)
    {
        if(this._fieldName_ != null)
        {
            this._fieldName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fieldName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comma_)
            + toString(this._fieldName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._fieldName_ == child)
        {
            this._fieldName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        if(this._fieldName_ == oldChild)
        {
            setFieldName((PFieldName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
