/* This file was generated by SableCC (http://www.sablecc.org/). */

package checker.node;

import checker.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyFieldList extends PFieldList
{

    public AEmptyFieldList()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AEmptyFieldList();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyFieldList(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
