/* This file was generated by SableCC (http://www.sablecc.org/). */

package checker.node;

import checker.analysis.*;

@SuppressWarnings("nls")
public final class AFieldAccessTerm extends PTerm
{
    private PNonLeftRecTerm _nonLeftRecTerm_;
    private TPeriod _period_;
    private TIdentifier _identifier_;

    public AFieldAccessTerm()
    {
        // Constructor
    }

    public AFieldAccessTerm(
        @SuppressWarnings("hiding") PNonLeftRecTerm _nonLeftRecTerm_,
        @SuppressWarnings("hiding") TPeriod _period_,
        @SuppressWarnings("hiding") TIdentifier _identifier_)
    {
        // Constructor
        setNonLeftRecTerm(_nonLeftRecTerm_);

        setPeriod(_period_);

        setIdentifier(_identifier_);

    }

    @Override
    public Object clone()
    {
        return new AFieldAccessTerm(
            cloneNode(this._nonLeftRecTerm_),
            cloneNode(this._period_),
            cloneNode(this._identifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFieldAccessTerm(this);
    }

    public PNonLeftRecTerm getNonLeftRecTerm()
    {
        return this._nonLeftRecTerm_;
    }

    public void setNonLeftRecTerm(PNonLeftRecTerm node)
    {
        if(this._nonLeftRecTerm_ != null)
        {
            this._nonLeftRecTerm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nonLeftRecTerm_ = node;
    }

    public TPeriod getPeriod()
    {
        return this._period_;
    }

    public void setPeriod(TPeriod node)
    {
        if(this._period_ != null)
        {
            this._period_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._period_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nonLeftRecTerm_)
            + toString(this._period_)
            + toString(this._identifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nonLeftRecTerm_ == child)
        {
            this._nonLeftRecTerm_ = null;
            return;
        }

        if(this._period_ == child)
        {
            this._period_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nonLeftRecTerm_ == oldChild)
        {
            setNonLeftRecTerm((PNonLeftRecTerm) newChild);
            return;
        }

        if(this._period_ == oldChild)
        {
            setPeriod((TPeriod) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
