/* This file was generated by SableCC (http://www.sablecc.org/). */

package checker.node;

import checker.analysis.*;

@SuppressWarnings("nls")
public final class AFieldDecl extends PFieldDecl
{
    private TIdentifier _classname_;
    private TIdentifier _fieldname_;
    private TSemicolon _semicolon_;

    public AFieldDecl()
    {
        // Constructor
    }

    public AFieldDecl(
        @SuppressWarnings("hiding") TIdentifier _classname_,
        @SuppressWarnings("hiding") TIdentifier _fieldname_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setClassname(_classname_);

        setFieldname(_fieldname_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new AFieldDecl(
            cloneNode(this._classname_),
            cloneNode(this._fieldname_),
            cloneNode(this._semicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFieldDecl(this);
    }

    public TIdentifier getClassname()
    {
        return this._classname_;
    }

    public void setClassname(TIdentifier node)
    {
        if(this._classname_ != null)
        {
            this._classname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._classname_ = node;
    }

    public TIdentifier getFieldname()
    {
        return this._fieldname_;
    }

    public void setFieldname(TIdentifier node)
    {
        if(this._fieldname_ != null)
        {
            this._fieldname_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fieldname_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._classname_)
            + toString(this._fieldname_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._classname_ == child)
        {
            this._classname_ = null;
            return;
        }

        if(this._fieldname_ == child)
        {
            this._fieldname_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._classname_ == oldChild)
        {
            setClassname((TIdentifier) newChild);
            return;
        }

        if(this._fieldname_ == oldChild)
        {
            setFieldname((TIdentifier) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
