/* This file was generated by SableCC (http://www.sablecc.org/). */

package checker.node;

import checker.analysis.*;

@SuppressWarnings("nls")
public final class ANonLeftRecTermTerm extends PTerm
{
    private PNonLeftRecTerm _nonLeftRecTerm_;

    public ANonLeftRecTermTerm()
    {
        // Constructor
    }

    public ANonLeftRecTermTerm(
        @SuppressWarnings("hiding") PNonLeftRecTerm _nonLeftRecTerm_)
    {
        // Constructor
        setNonLeftRecTerm(_nonLeftRecTerm_);

    }

    @Override
    public Object clone()
    {
        return new ANonLeftRecTermTerm(
            cloneNode(this._nonLeftRecTerm_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANonLeftRecTermTerm(this);
    }

    public PNonLeftRecTerm getNonLeftRecTerm()
    {
        return this._nonLeftRecTerm_;
    }

    public void setNonLeftRecTerm(PNonLeftRecTerm node)
    {
        if(this._nonLeftRecTerm_ != null)
        {
            this._nonLeftRecTerm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nonLeftRecTerm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nonLeftRecTerm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nonLeftRecTerm_ == child)
        {
            this._nonLeftRecTerm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nonLeftRecTerm_ == oldChild)
        {
            setNonLeftRecTerm((PNonLeftRecTerm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
