/* This file was generated by SableCC (http://www.sablecc.org/). */

package checker.analysis;

import java.util.*;
import checker.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    public void caseAProg(AProg node)
    {
        defaultCase(node);
    }

    public void caseAClassDecl(AClassDecl node)
    {
        defaultCase(node);
    }

    public void caseAFieldDecl(AFieldDecl node)
    {
        defaultCase(node);
    }

    public void caseAConstructorDecl(AConstructorDecl node)
    {
        defaultCase(node);
    }

    public void caseAMethodDecl(AMethodDecl node)
    {
        defaultCase(node);
    }

    public void caseAParamArgsParamDeclList(AParamArgsParamDeclList node)
    {
        defaultCase(node);
    }

    public void caseAEmptyParamDeclList(AEmptyParamDeclList node)
    {
        defaultCase(node);
    }

    public void caseAIdentParamArg(AIdentParamArg node)
    {
        defaultCase(node);
    }

    public void caseAThisParamArg(AThisParamArg node)
    {
        defaultCase(node);
    }

    public void caseACommaParamArgList(ACommaParamArgList node)
    {
        defaultCase(node);
    }

    public void caseAFieldListFieldList(AFieldListFieldList node)
    {
        defaultCase(node);
    }

    public void caseAEmptyFieldList(AEmptyFieldList node)
    {
        defaultCase(node);
    }

    public void caseAFieldName(AFieldName node)
    {
        defaultCase(node);
    }

    public void caseACommaField(ACommaField node)
    {
        defaultCase(node);
    }

    public void caseAThisFieldAssig(AThisFieldAssig node)
    {
        defaultCase(node);
    }

    public void caseANonLeftRecTermTerm(ANonLeftRecTermTerm node)
    {
        defaultCase(node);
    }

    public void caseAFieldAccessTerm(AFieldAccessTerm node)
    {
        defaultCase(node);
    }

    public void caseAMethodCallTerm(AMethodCallTerm node)
    {
        defaultCase(node);
    }

    public void caseACastTerm(ACastTerm node)
    {
        defaultCase(node);
    }

    public void caseAVariableNonLeftRecTerm(AVariableNonLeftRecTerm node)
    {
        defaultCase(node);
    }

    public void caseAThisNonLeftRecTerm(AThisNonLeftRecTerm node)
    {
        defaultCase(node);
    }

    public void caseAObjectCreationNonLeftRecTerm(AObjectCreationNonLeftRecTerm node)
    {
        defaultCase(node);
    }

    public void caseABracketNonLeftRecTerm(ABracketNonLeftRecTerm node)
    {
        defaultCase(node);
    }

    public void caseATermListTermList(ATermListTermList node)
    {
        defaultCase(node);
    }

    public void caseAEmptyTermList(AEmptyTermList node)
    {
        defaultCase(node);
    }

    public void caseACommaTerm(ACommaTerm node)
    {
        defaultCase(node);
    }

    public void caseTTclass(TTclass node)
    {
        defaultCase(node);
    }

    public void caseTExtends(TExtends node)
    {
        defaultCase(node);
    }

    public void caseTSuper(TSuper node)
    {
        defaultCase(node);
    }

    public void caseTThis(TThis node)
    {
        defaultCase(node);
    }

    public void caseTNew(TNew node)
    {
        defaultCase(node);
    }

    public void caseTReturn(TReturn node)
    {
        defaultCase(node);
    }

    public void caseTLBrace(TLBrace node)
    {
        defaultCase(node);
    }

    public void caseTRBrace(TRBrace node)
    {
        defaultCase(node);
    }

    public void caseTSemicolon(TSemicolon node)
    {
        defaultCase(node);
    }

    public void caseTComma(TComma node)
    {
        defaultCase(node);
    }

    public void caseTLPar(TLPar node)
    {
        defaultCase(node);
    }

    public void caseTRPar(TRPar node)
    {
        defaultCase(node);
    }

    public void caseTLSq(TLSq node)
    {
        defaultCase(node);
    }

    public void caseTRSq(TRSq node)
    {
        defaultCase(node);
    }

    public void caseTPeriod(TPeriod node)
    {
        defaultCase(node);
    }

    public void caseTEq(TEq node)
    {
        defaultCase(node);
    }

    public void caseTNewLine(TNewLine node)
    {
        defaultCase(node);
    }

    public void caseTBlank(TBlank node)
    {
        defaultCase(node);
    }

    public void caseTIdentifier(TIdentifier node)
    {
        defaultCase(node);
    }

    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
